sudo: false

# Use Maven
language: java

cache:
  directories:
    - $HOME/.m2

before_install:
  - if [ ! -d "$HOME/.m2/repository/org/spigotmc" ]; then ./installSpigot.sh 1.12 ; else echo "Not compiling Spigot because it is already in our maven" ; fi

install:
  - mvn install -DfinalName=release -DskipTests=true -Dmaven.javadoc.skip=true -B -V

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_OAUTH_TOKEN
    file: target/PrisonRanks.jar
  skip_cleanup: true
