language: java

install:
    - gradle assemble
    - git clone https://github.com/GABRYCA/Prison_Ranks.git
    - wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
    - java -jar BuildTools.jar | grep -vE "[^/ ]*/[^/ ]*\s*KB\s*$" | grep -v "^\s*$"
    - find Spigot/Spigot-Server/target/*.jar
    
os: linux

dist: trusty

jdk: oraclejdk8

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    
    script:
    - gradle check
    
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_OAUTH_TOKEN
    file: target/PrisonRanks.jar
  skip_cleanup: true 
