version: 0.1.{build}

os: Visual Studio 2014 CTP4

environment:
  matrix:
    # 64 bit
    - PLATFORM: x64
      CONFIGURATION: Release
      JAVA_HOME: C:\Program Files\Java\jdk1.8.0
      RDP: "no"

    # 32 bit
    - PLATFORM: x86
      CONFIGURATION: Release
      JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0

install:

  # Install Maven
  - set MVN_VERSION=3.6.0
  - set PATH=%PATH%;C:\bin\apache-maven-%MVN_VERSION%\bin
  - if not exist "C:\bin\apache-maven-%MVN_VERSION%\bin\*.*" (echo Maven %MVN_VERSION% not installed, so install it & cinst maven -Version %MVN_VERSION%) else (echo  Maven %MVN_VERSION% already installed)

build_script:
  - mvn clean package
test_script:
  - mvn clean install
cache:
  - C:\bin\apache-maven-3.6.0
  - C:\Users\appveyor\.m2
on_success:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/k3rn31p4nic/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 success $env:WEBHOOK_URL
on_failure:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/k3rn31p4nic/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 failure $env:WEBHOOK_URL