Settings:
  Prestiges-enabled: true
  Fireworks-rankup: true
  Fireworks-prestige: true
  Ranks-GUI-Permission: false
  Prestiges-GUI-Permission: false
  Default-Rank-Material: "TRIPWIRE_HOOK"
  Default-Prestige-Material: "TRIPWIRE_HOOK"
  Default-NotReachedRank-Material: "REDSTONE_BLOCK"
  Default-NotReachedPrestige-Material: "REDSTONE_BLOCK"
  Rankup-Broadcast: true
  Prestige-Broadcast: true

Permissions:
  Ranks-GUI-Permission: "PrisonRanks.Ranks"
  Prestiges-GUI-Permission: "PrisonRanks.Prestiges"
  Admin-Management: "PrisonRanks.Admin"
