name: PrisonRanks
version: 0.2
author: GABRYCA
main: it.gabryca.prison_ranks.Main
website: https://www.gabryca.tk
api-version: 1.13
depend: [Vault, PlaceholderAPI]
softdepend: [MVdWPlaceholderAPI]
commands:
  PrisonRanks:
    usage: /<command>
    description: Give you a list of commands
  Rankup:
    usage: /<command>
    description: Command for rankup
  Prestige:
    usage: /<command>
    description: Command for prestige
  AddRank:
    usage: /<command> <rank> <prefix> <price>
    description: Add a rank
  AddRankupCommand:
    usage: /<command> <rank> <rankup_command>
    description: Add a command when rankup
  AddPrestige:
    usage: /<command> <prestige> <prefix> <price>
    description: Add a prestige
  AddPrestigeCommand:
    usage: /<command> <prestige> <prestige_command>
    description: Add a command when prestige
  DelRank:
    usage: /<command> <rank>
    description: Delete a rank
  DelRankupCommand:
    usage: /<command> <rank> <id>
    description: Delete a command when rankup
  DelPrestige:
    usage: /<command> <prestige>
    description: Delete a prestige
  DelPrestigeCommand:
    usage: /<command> <prestige> <id>
    description: Delete a command when prestige
  ChangeRankPrefix:
    usage: /<command> <rank> <New_Prefix>
    description: Change Rank Prefix
  ChangeRankPrice:
    usage: /<command> <rank> <New_Price>
    description: Change rankup price
  ChangePrestigePrefix:
    usage: /<command> <prestige> <New_Prefix>
    description: Change prestige prefix
  ChangePrestigePrice:
    usage: /<command> <prestige> <New_Price>
    description: Change prestige price
  Ranks:
    usage: /<command>
    description: Open a GUI with all the ranks
  Prestiges:
    usage: /<command>
    description: Open a GUI with prestiges
  ResetPlayerPrestige:
    usage: /<command> <Name>
    description: Reset a player Prestige
  ResetPlayerRank:
    usage: /<command> <Name>
    description: Reset a player Rank
  ChangePlayerPrestige:
    usage: /<command> <PrestigeNumber>
    description: Change a Player Prestige to another
  ChangePlayerRank:
    usage: /<command> <RankNumber>
    description: Change a Player Rank to another
  RanksManager:
    usage: /<command>
    description: Open a GUI where you can manage ranks