Settings:
  Prestiges-enabled: true
  Fireworks-rankup: true
  Ranks-GUI-Permission: false
  Default-Rank-Material: "TRIPWIRE_HOOK"
  Default-NotReachedRank-Material: "REDSTONE_BLOCK"
  Rankup-Broadcast: true

Permissions:
  Ranks-GUI-Permission: "PrisonRanks.Ranks"
  Admin-Management: "PrisonRanks.Admin"
