name: Prison_Ranks

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Gradle Command
      uses: eskatos/gradle-command-action@v1
    - name: Update Gradle Wrapper
      uses: rahulsom/gradle-up@v0.1.0
    - name: Set up wrapper
      run: gradle wrapper
    - name: Prison_Ranks 
      run: chmod +x ./gradlew build
